/**
 * App UI copy, in every language the app speaks. Components read it with useUI() (lib/locale.ts);
 * the letters themselves have their own dictionary (lib/i18n.ts). English is the source: every
 * other language is typed against it, so a missing string is a compile error.
 */
import type { BlockType, Kind, Lang } from "./model";
import type { STYLE_GROUPS } from "./styles";
import { de, es, fr, it, pt } from "./ui-locales";

/** English names, also used by the API and agent docs (stable, not translated). */
export const KIND_LABEL: Record<Kind, string> = {
  birthday: "Birthday", wedding: "Wedding", party: "Party", baby: "Baby shower",
  dinner: "Dinner", graduation: "Graduation", event: "Event", letter: "Letter",
};

export const BLOCK_LABEL: Record<BlockType, string> = {
  heading: "Title", text: "Text", image: "Image", date: "Date", place: "Place",
  countdown: "Countdown", link: "Link", qr: "QR code", rsvp: "RSVP", agenda: "Schedule",
  dress: "Dress code", gift: "Gifts", signature: "Signature", divider: "Divider", music: "Music", stamp: "Stamp",
};

const en = {
  kinds: KIND_LABEL,
  blocks: BLOCK_LABEL,
  groups: { Classic: "Classic", Elegant: "Elegant", Modern: "Modern", Playful: "Playful", Retro: "Retro" } as Record<(typeof STYLE_GROUPS)[number], string>,
  create: "New letter",
  blank: "Blank",
  letters: "Your letters",
  send: "Send",
  share: "Share",
  copy: "Copy link",
  copied: "Copied",
  preview: "Preview",
  edit: "Edit",
  undo: "Undo",
  theme: "Style",
  home: "Home",
  back: "Back",
  done: "Done",
  publish: "Seal & get link",
  update: "Update link",
  publishing: "Sealing…",
  print: "Print / PDF",
  delete: "Delete",
  confirmDelete: "Tap again to delete",
  confirmUnpublish: "Tap again to delete it and its links",
  rsvp: { yes: "Coming", maybe: "Maybe", no: "Can't come", pending: "No answer yet" },
  duplicateName: "Two guests share this name: each gets their own link.",
  duplicate: "Duplicate",
  moveUp: "Move up",
  moveDown: "Move down",
  add: "Add",
  editElsewhere: "Copy edit link for another device",
  error: "Something went wrong. Try again.",
  limitReached: "Limit reached — try again in a while.",
  offline: "You're offline",
  to: "To",
  seal: "Seal",
  language: "Letter language",
  format: "Format",
  linkOnly: "link only",
  steps: ["Language", "Style", "Start"] as string[],
  stepOf: (n: number, of: number, name: string) => `Step ${n} of ${of}: ${name}`,
  envelopesForLinks: "Envelopes are for links",
  exampleGuest: "Example guest",
  useAsExample: "Use as example",
  turnOver: "Turn over",
  front: "Front",
  firstInitial: "First initial",
  secondInitial: "Second initial",
  email: "Email",
  emojiSets: { wear: "Wear", colors: "Colors", nature: "Nature", mood: "Mood" },
  replay: "Replay",
  saveQr: "Save QR code",
  clear: "Clear",
  // style panel
  customize: "Customize",
  accent: "Accent",
  paper: "Paper",
  ink: "Text",
  envelope: "Envelope",
  envelopePaper: "Envelope paper",
  styleDefault: "Style default",
  auto: "auto",
  fontTitles: "Titles",
  fontText: "Text",
  // seal
  shape: "Shape",
  mark: "Mark",
  noSeal: "No seal",
  plainWax: "Plain wax",
  initials: "Initials",
  // block editors
  size: "Size",
  alignment: "Alignment",
  italic: "Italic",
  border: "Border",
  borders: { auto: "Style", none: "None", rule: "Line", ornate: "Double" },
  countdownTarget: "Countdown target",
  icon: "Icon",
  replyChannel: "Reply channel",
  dividerStyle: "Divider style",
  stamp: "Stamp",
  boardWordPh: "Linen",
  illustrationStyle: "Illustration style",
  imagine: "Generate",
  imagining: "Generating…",
  describe: "Describe a picture… e.g. a dragon blowing out candles",
  camera: "Camera",
  gallery: "Photos",
  removeImage: "Remove image",
  styles: { storybook: "Storybook", medieval: "Medieval", sketch: "Sketch", photo: "Photo" },
  shapes: { wide: "Wide", square: "Square", round: "Round" },
  allDay: "All day",
  start: "Starts", end: "Ends (optional)", endBeforeStart: "Ends before it starts",
  followDate: "Event date", customDate: "Custom date", noDateBlock: "Add a Date block to follow it",
  placeName: "Name (e.g. Casa Lucía)", address: "Address — used for the map",
  linkUrl: "Link", linkLabel: "Button text (optional)",
  qrData: "QR content (empty = this letter's link)", qrCaption: "Caption (optional)",
  rsvpTo: { whatsapp: "WhatsApp number", sms: "Phone number", email: "Email address" },
  rsvpHint: "Guests reply with one tap; answers arrive on this channel.",
  deadline: "Reply by (optional)",
  scheduleTime: "Time", scheduleWhat: "What happens", addItem: "Add item",
  scheduleExamples: ["Ceremony", "Dinner", "Dancing"],
  dressText: "Dress code (e.g. Cocktail, all white)",
  board: { color: "Color", emoji: "Emoji", text: "Word", image: "Picture" },
  giftText: "Message", giftIban: "IBAN / Bizum / PayPal", giftUrl: "Registry link (optional)",
  musicUrl: "Spotify, YouTube or SoundCloud link", musicUnsupported: "Paste a Spotify, YouTube or SoundCloud link",
  signature: "Your name",
  headingPh: "Title", textPh: "Write something…",
  sizes: { md: "Small", lg: "Medium", xl: "Large" },
  align: { center: "Centered", left: "Left" },
  dividers: { flourish: "Flourish", stars: "Stars", line: "Line" },
  linkIcons: { link: "Link", gift: "Gift", music: "Music", video: "Video", map: "Map", camera: "Photos" },
  guests: {
    title: "Guests",
    add: "Add guest",
    namePh: "Guest name",
    contactPh: "Phone or email (optional)",
    paste: "Paste a list",
    pastePh: "One guest per line:\nLucía, +34 600 000 000\nTom, tom@mail.com",
    importList: "Add these",
    contacts: "From contacts",
    insertName: "Guest name",
    hint: "Each guest gets their own letter. Use “Guest name” in any text to address them.",
    notUsed: "The letter doesn't mention the guest yet.",
    addGreeting: "Add their name at the top",
    fallback: "Without a guest, {name} reads as",
    previewAs: "Example guest:",
    count: (n: number) => `${n} guest${n === 1 ? "" : "s"}`,
  },
  out: {
    link: "Link",
    image: "Image",
    sent: "Sent",
    markSent: "Mark as sent",
    sendTo: "Send",
    copyAll: "Copy all links",
    sendNext: "Send next",
    csv: "Guest links (CSV)",
    generic: "Letter without a name",
    download: "Download image",
    shareImage: "Share image",
    zip: (n: number) => `All ${n} images (ZIP)`,
    rendering: (d: number, n: number) => `Drawing ${d}/${n}…`,
    imageNote: "One image per guest, in a ZIP when there are many. PNG, ready to send.",
    progress: (s: number, n: number) => `${s} of ${n} sent`,
  },
  view: { link: "Link", image: "Image" },
  interactive: "Show buttons in the link",
  assistant: {
    label: "Describe your invitation",
    placeholder: "My birthday on Saturday 17 October, at a house in a pine forest by a lake… with a QR to our WhatsApp group, for several friends",
    go: "Make it",
    working: "Writing your letter…",
    failed: "That didn't work. Try again, or start from the envelope.",
    limited: "Too many tries for now. Start from the envelope below.",
    note: "From the assistant",
  },
  tile: { published: "Published", edited: (when: string) => `Edited ${when}` },
  // after sending
  thanks: {
    howWasIt: "Sent! How was it?",
    stars: (n: number) => `${n} star${n === 1 ? "" : "s"}`,
    thankYou: "Thank you! I'm glad it helped.",
    passItOn: "Magic Envelope is free and ad-free, and it grows through recommendations: if you liked it, share it.",
    close: "Close",
  },
  // public site
  site: {
    tagline: "Free invitations that arrive in a sealed envelope",
    ratings: (n: number) => `${n} rating${n === 1 ? "" : "s"}`,
    makeInvitation: "Make an invitation",
    forAgents: "For agents",
    apiDocs: "API & MCP docs",
    freeForever: "Free, forever",
    noAds: "No account, no ads. If it made someone smile:",
    coffee: "Buy me a coffee",
    madeBy: "made by",
    createFree: "Create yours — free",
    faq: "Questions",
    languages: "Languages",
  },
};

export type UIText = typeof en;

export const UI_TEXT: Record<Lang, UIText> = { en, es, fr, pt, it, de };

/** English copy, for server code that has no locale (API errors, agent docs). */
export const UI = en;
